# Generated by Django 3.1.5 on 2021-06-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=5)),
                ('runTime', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=50)),
                ('poster', models.CharField(max_length=1000)),
            ],
        ),
    ]
