# Generated by Django 3.1.5 on 2021-06-13 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='runTime',
        ),
    ]
