# Generated by Django 3.1.5 on 2021-06-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_movie_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
