# Generated by Django 3.1.5 on 2021-07-14 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210619_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.TextField(default=140, max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(default=140, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.movie'),
            preserve_default=False,
        ),
    ]
