# Generated by Django 3.1.5 on 2021-07-18 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210717_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='downvotes',
            new_name='dislikes',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='upvotes',
            new_name='likes',
        ),
    ]
