# Generated by Django 3.1.5 on 2021-07-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210718_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='total_rating_points',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='total_reviews',
        ),
    ]
